app = "app-thrumming-glade-1120"
primary_region = "iad"

[build]
  image = "app-thrumming-glade-1120"

[http_service]
  internal_port = 3000
  force_https = true

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[env]
  NODE_ENV = "production"
